### ISSUE TITLE
Contact to developer? Support?

### ISSUE THREAD

**Issue by strolli** [vincentrou/ifm_o3m151#1]
Is there a way to get direct contact to developer please?

I am working at ifm as application engineer for O3M and I am very happy to see that someone as written a ROS interface. I would like to get in contact to share know-how and experiences. Thanks.

**Comment by vincentrou** [comment]
I am the developper of this ROS package.
You can found information about my contact and the software license here https://github.com/vincentrou/ifm_o3m151/blob/master/o3m151_driver/package.xml

To be fair, the protocol of the camera O3M is not well documented (as far as I know), so it was not very easy to create this package.

Further more the  amplitude information is still unusable cf https://github.com/vincentrou/ifm_o3m151/commit/6f6d8c142c5f21a4a57fdc7f8efa3c35e9168993

So it could be great if at ifm you can truly support this camera on ROS !

**Comment by strolli** [comment]
Thank you for the Feedback... Good to see that someone is using O3M even with ROS.
Pretty sure I will have a personal meeting with you/your contracting entity very soon.

Nevertheless... What is the issue with the amplitude? Why is it not working?

**Comment by strolli** [comment]
Let's close this issue... The discussion should not be take further in this open issue. Right?
